# Generated by Django 4.2.4 on 2023-09-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes_dosage_form_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
