# Generated by Django 4.2.4 on 2023-09-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='MedicineReminder',
        ),
        migrations.RenameField(
            model_name='medicinereminder',
            old_name='regimenNote',
            new_name='regimen_note',
        ),
    ]
