# Generated by Django 4.2.4 on 2023-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicinereminder_dosage_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injectable', 'Injectable')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='dosage_frequency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicinereminder',
            name='dosage_unit_of_measure',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('volumetric', 'Volumetric/mL')], max_length=256, null=True),
        ),
    ]
