# Generated by Django 4.2.4 on 2023-09-26 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medicinereminder_dosage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='first_time_of_intake',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
