# Generated by Django 4.2.4 on 2023-09-29 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_medicinereminder_dosage_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='is_chronic_or_acute',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='route_of_administration',
            field=models.CharField(choices=[('oral', 'Orally'), ('parentral/im', 'Intra-muscular'), ('parentral/sc', 'Subcutaneous'), ('parentral/iv', 'Intravenous')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='stopped_by_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
