# Generated by Django 4.2.4 on 2023-10-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicinereminder_is_chronic_or_acute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinereminder',
            old_name='per_day_or_week_or_month',
            new_name='periodic_interval',
        ),
    ]
