# Generated by Django 4.2.4 on 2024-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_per_day_or_week_or_month_medicinereminder_periodic_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='stopped_by_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
